function Header (){

    return(
        <header>
            <div className="menu-container">
                <nav className="menu">
                    <ul className="menu-links">
                        <li><a href="#">Register</a></li>
                        <li><a href="#">Login</a></li>
                    </ul>
                </nav>

            </div>
            <div className="header-container">
                <h1 className="header">AI Checker</h1>
                <p className="Writing">Verify whether or not writing was generated by artificial intelligence</p>
            </div>
        </header>
    );

}

export default Header