import React from "react";
import {Outlet, Link} from "react-router-dom";

function Header (){

    return(
        <header>
            <div className="menu-container">
                <nav className="menu">
                    <ul className="menu-links">
                        <li>
                            <Link to="/login">Login</Link>
                        </li>
                        <li>
                            <Link to="/register">Register</Link>
                        </li>
                    </ul>
                </nav>
                
                <Outlet />

            </div>
            <div className="header-container">
                <h1 className="header">AI Checker</h1>
                <p className="Writing">Verify whether or not writing was generated by artificial intelligence</p>
            </div>
        </header>
    );

}

export default Header